name = "CATpack"
author = "MAnitosik"
version = "v1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8de4eeda6d889c611b0a36e2246131ca1dd5387b92b8dec72481a1f9c312a43d"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
