name = "CATpack"
author = "MAnitosik"
version = "v1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87ad77c91f130fd3d9f02188cbe357f0681d134e5f5a7c91e1f810e748d84731"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
